name: 'Run Icon Update'

on:
  workflow_call:
    secrets:
      FIGMA_ACCESS_TOKEN:
        description: "The personal access token created in Figma"
        required: true

      FIGMA_FILE_ID:
        description: "The file id for the Figma file"
        required: true

jobs:
  update-icons:
    runs-on: ubuntu-latest
    outputs:
      bumpType: ${{ steps.version-bump.outputs.VERSION_BUMP_TYPE}}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Configure user
        run: |
          git config user.name "Kajabi Automation Bot"
          git config user.email "dev+github-bot@kajabi.com"

      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - name: Cache node_modules
        uses: actions/cache@v3
        id: cache-node-modules
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Set SHA
        uses: nrwl/nx-set-shas@v3

      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
        shell: bash

      - name: Get current date
        id: date
        run: echo "current_date=$(date --rfc-3339=date)" >> $GITHUB_ENV

      - name: Running Icon Export
        run: npx nx run icons:update
        env:
          FIGMA_ACCESS_TOKEN: ${{ secrets.FIGMA_ACCESS_TOKEN }}
          FIGMA_FILE_ID: ${{ secrets.FIGMA_FILE_ID }}

      - name: Determine Major or Minor version bump
        id: version-bump
        run: |
          echo "VERSION_BUMP_TYPE=$(node ./.scripts/update-icon-version.js)" >> $GITHUB_OUTPUT
        shell: bash

  release:
    needs: update-icons
    uses: ./.github/workflows/release-icons.yml
    if: needs.update-icons.outputs.bumpType != ''
    with:
      tag: 'nightly'
      version: ${{ needs.update-icons.outputs.bumpType }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

